// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQqHqhdYeci5VP2Chw4r9zDKAoJXd3QMI',
    appId: '1:1046391219452:web:b9aae87e958b3f290de379',
    messagingSenderId: '1046391219452',
    projectId: 'chungchunon-android-dd695',
    authDomain: 'chungchunon-android-dd695.firebaseapp.com',
    databaseURL: 'https://chungchunon-android-dd695-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chungchunon-android-dd695.appspot.com',
    measurementId: 'G-P1LXY0F50Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzOJ_O-XrreKdkYh9MF66Cck7urPZ4hA',
    appId: '1:1046391219452:android:589ccf7c09966bcb0de379',
    messagingSenderId: '1046391219452',
    projectId: 'chungchunon-android-dd695',
    databaseURL: 'https://chungchunon-android-dd695-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chungchunon-android-dd695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Fia5MVeGBaD9Z1vWKd6KN00cPTlOSY4',
    appId: '1:1046391219452:ios:008741b73a40b43e0de379',
    messagingSenderId: '1046391219452',
    projectId: 'chungchunon-android-dd695',
    databaseURL: 'https://chungchunon-android-dd695-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chungchunon-android-dd695.appspot.com',
    androidClientId: '1046391219452-2chv1q1ssuhl399lbouifpro9n861hrj.apps.googleusercontent.com',
    iosClientId: '1046391219452-jhbg29keh7kl7dbhkp7smk05jf3u98b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.onldoccAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Fia5MVeGBaD9Z1vWKd6KN00cPTlOSY4',
    appId: '1:1046391219452:ios:eaa4ebbb5160bff10de379',
    messagingSenderId: '1046391219452',
    projectId: 'chungchunon-android-dd695',
    databaseURL: 'https://chungchunon-android-dd695-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chungchunon-android-dd695.appspot.com',
    androidClientId: '1046391219452-2chv1q1ssuhl399lbouifpro9n861hrj.apps.googleusercontent.com',
    iosClientId: '1046391219452-1bj6mr60ac76dmjs74bhe4av0he11lnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.onldoccAdmin.RunnerTests',
  );
}
