name: gh-pages

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /onldocc_admin/
      - name: Create.env
        shell: bash
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANONKEY: ${{ secrets.SUPABASE_ANONKEY }}
        run: |
          touch .env
          echo '{
            "SUPABASE_URL" : "${{ secrets.SUPABASE_URL }}",
            "SUPABASE_ANONKEY" : "${{ secrets.SUPABASE_ANONKEY }}"
          }' > env.json
