name: gh-pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANONKEY: ${{ secrets.SUPABASE_ANONKEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /onldocc_admin/
      - name: Write dev.json
        run: |
          echo "$SUPABASE_URL" | base64 -d > .env
          echo "$SUPABASE_ANONKEY" | base64 -d > .env
